# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "submit to internal track in Google Play Store"
  lane :internal do
    Dir.chdir "../.." do sh("flutter", "build", "appbundle", "--release") end # Call Flutter Build
    upload_to_play_store(
      track: 'internal',
      version_code: flutter_version()["version_code"],
      aab: '../build/app/outputs/bundle/prodRelease/app-prod-release.aab',
      skip_upload_screenshots: true,
      skip_upload_images: true
    )
  end

  desc "submit to Firebase App Distribution"
  lane :distribute do
    Dir.chdir "../.." do sh("flutter", "build", "apk", "--release") end # Call Flutter Build
    puts ENV
  
    firebase_app_distribution(
        app: "1:6951668153:android:81bb18aef9d3428cf60e68",
        firebase_cli_token: ENV['FIREBASE_CLI_TOKEN'],
        android_artifact_path: '../build/app/outputs/flutter-apk/app-dev-release.apk',
        groups: "qa-team"
    )
  end
end
